disabled_rules:
- force_cast
- identifier_name
- trailing_whitespace
- multiple_closures_with_trailing_closure
- unused_closure_parameter
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

force_try:
  severity: warning # explicitly. Give warning only for force try

line_length:
- 200 # warning
- 300 # error

type_body_length:
- 300 # warning
- 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 800
large_tuple: # warn user when using 3 values in tuple, give error if there are 4
- 3
- 4